/** Olfactive notes: slug → [English, Arabic] */
export const NOTES: Record<string, [string, string]> = {
  saffron: ["Saffron", "زعفران"],
  "black-pepper": ["Black Pepper", "فلفل أسود"],
  "pink-pepper": ["Pink Pepper", "فلفل وردي"],
  oud: ["Agarwood (Oud)", "عود"],
  "cambodian-oud": ["Cambodian Oud", "عود كمبودي"],
  rose: ["Rose", "ورد"],
  "taif-rose": ["Taif Rose", "ورد طائفي"],
  "damask-rose": ["Damask Rose", "ورد دمشقي"],
  "rose-otto": ["Kannauj Rose Otto", "زيت ورد قنّوج"],
  amber: ["Amber", "عنبر"],
  ambergris: ["Ambergris", "عنبر رمادي"],
  leather: ["Leather", "جلد"],
  sandalwood: ["Mysore Sandalwood", "صندل ميسور"],
  bergamot: ["Bergamot", "برغموت"],
  peony: ["Peony", "فاوانيا"],
  "white-musk": ["White Musk", "مسك أبيض"],
  musk: ["Musk", "مسك"],
  cedar: ["Cedarwood", "خشب الأرز"],
  cinnamon: ["Cinnamon", "قرفة"],
  mandarin: ["Mandarin", "يوسفي"],
  labdanum: ["Labdanum", "لادن"],
  benzoin: ["Benzoin", "جاوي"],
  vanilla: ["Vanilla", "فانيليا"],
  tonka: ["Tonka Bean", "حبوب التونكا"],
  pear: ["Pear", "كمثرى"],
  aldehydes: ["Aldehydes", "ألدهيدات"],
  iris: ["Iris", "سوسن"],
  cashmeran: ["Cashmere Wood", "خشب الكشمير"],
  ambrette: ["Ambrette Seed", "بذور العنبريّة"],
  cardamom: ["Cardamom", "هيل"],
  jasmine: ["Jasmine", "ياسمين"],
  "jasmine-sambac": ["Jasmine Sambac (Mogra)", "فلّ"],
  vetiver: ["Vetiver (Khus)", "نجيل الهند (خس)"],
  petrichor: ["First Rain", "رائحة المطر الأول"],
  "baked-earth": ["Sun-baked Earth", "تراب محمّص بالشمس"],
  clove: ["Clove", "قرنفل"],
  kewda: ["Kewda (Pandanus)", "كيورا"],
  herbs: ["Himalayan Herbs", "أعشاب الهيمالايا"],
  kadam: ["Kadam Blossom", "زهر الكدم"],
  "green-leaves": ["Green Leaves", "أوراق خضراء"],
  lime: ["Lime", "ليم"],
  moss: ["Oakmoss", "طحلب البلوط"],
  lily: ["Lily", "زنبق"],
  basil: ["Basil", "ريحان"],
  nutmeg: ["Nutmeg", "جوزة الطيب"],
  patchouli: ["Patchouli", "باتشولي"],
  plum: ["Plum", "برقوق"],
  raspberry: ["Raspberry", "توت العليق"],
  tuberose: ["Tuberose", "مسك الروم"],
  "orange-blossom": ["Orange Blossom", "زهر البرتقال"],
  praline: ["Praline", "برالين"],
  "sea-salt": ["Sea Salt", "ملح البحر"],
  grapefruit: ["Grapefruit", "جريب فروت"],
  sage: ["Sage", "مريمية"],
  "marine-accord": ["Marine Breeze", "نسيم البحر"],
  driftwood: ["Driftwood", "خشب الشاطئ"],
  neroli: ["Neroli", "نيرولي"],
  lemon: ["Lemon", "ليمون"],
  petitgrain: ["Petitgrain", "بتيتغرين"],
  henna: ["Henna", "حنّاء"],
  "green-tea": ["Green Tea", "شاي أخضر"],
  mint: ["Mint", "نعناع"],
  cucumber: ["Cucumber", "خيار"],
  lavender: ["Lavender", "خزامى"],
  coffee: ["Arabian Coffee", "قهوة عربية"],
  frankincense: ["Frankincense", "لبان"],
  chamomile: ["Chamomile", "بابونج"],
  peppermint: ["Peppermint", "نعناع فلفلي"],
  rosemary: ["Rosemary", "إكليل الجبل"],
  argan: ["Argan", "أرغان"],
  rosehip: ["Rosehip", "ثمر الورد"],
  "kumkumadi-saffron": ["Kumkumadi Saffron", "زعفران كومكومادي"],
  geranium: ["Rose Geranium", "إبرة الراعي"],
  "ylang-ylang": ["Ylang-Ylang", "يلانغ يلانغ"],
  eucalyptus: ["Eucalyptus", "أوكالبتوس"],
  "tea-tree": ["Tea Tree", "شجرة الشاي"],
  incense: ["Incense (Bakhoor)", "بخور"],
  "orris-butter": ["Orris Butter", "زبدة السوسن"],
};
