type Kind = "FRAGRANCE" | "THERAPY" | "GIFT_SET" | "DISCOVERY_SET";
type Form = "PERFUME" | "ATTAR" | "OIL" | "SET";
type Family =
  | "OUD" | "FLORAL" | "WOODY" | "AMBER" | "MUSK" | "CITRUS"
  | "FRESH" | "SPICY" | "GOURMAND" | "EARTHY" | "HERBAL";
type Mood = "CALM" | "ENERGETIC" | "CONFIDENT" | "FOCUSED" | "ROMANTIC" | "BALANCED";
type Season = "SPRING" | "SUMMER" | "MONSOON" | "AUTUMN" | "WINTER";
type Time = "DAY" | "NIGHT";
type Occasion = "EVERYDAY" | "OFFICE" | "DATE" | "CELEBRATION" | "PRAYER" | "TRAVEL";
type Need = "STRESS" | "SLEEP" | "FOCUS" | "SKIN_HAIR" | "BALANCE";

export type SeedProduct = {
  slug: string;
  name: string;
  nameAr: string;
  kind: Kind;
  forms: Form[];
  tier?: "classic" | "luxe";
  family?: Family;
  gender: "MEN" | "WOMEN" | "UNISEX";
  shape?: "facet" | "round" | "column" | "arch";
  color: string;
  moods?: Mood[];
  seasons?: Season[];
  times?: Time[];
  occasions?: Occasion[];
  needs?: Need[];
  longevity?: number;
  sillage?: number;
  intensity?: number;
  notes?: { top: string[]; heart: string[]; base: string[] };
  tagline: string;
  taglineAr: string;
  story: string;
  storyAr: string;
  bestseller?: boolean;
  isNew?: boolean;
  featured?: boolean;
  offer?: boolean;
  sampleable?: boolean;
  /** For sets: fixed price in rupees and its contents */
  setPrice?: number;
  setMrp?: number;
  setContents?: string;
  setContentsAr?: string;
  pairs?: string[];
};

const ALL_SEASONS: Season[] = ["SPRING", "SUMMER", "MONSOON", "AUTUMN", "WINTER"];

export const PRODUCTS: SeedProduct[] = [
  // ─── Fragrances ──────────────────────────────────────────────────────────
  {
    slug: "oud-al-layl",
    name: "Oud al-Layl",
    nameAr: "عود الليل",
    kind: "FRAGRANCE",
    forms: ["PERFUME", "ATTAR"],
    tier: "luxe",
    family: "OUD",
    gender: "UNISEX",
    shape: "column",
    color: "#4a2a17",
    moods: ["CONFIDENT", "ROMANTIC"],
    seasons: ["AUTUMN", "WINTER"],
    times: ["NIGHT"],
    occasions: ["CELEBRATION", "DATE"],
    longevity: 5, sillage: 5, intensity: 5,
    notes: { top: ["saffron", "black-pepper"], heart: ["cambodian-oud", "taif-rose"], base: ["amber", "leather", "sandalwood"] },
    tagline: "The hour after midnight, bottled.",
    taglineAr: "الساعة التي تلي منتصف الليل، في قارورة.",
    story:
      "A slow-burning oud from Cambodian agarwood, lit by saffron and softened with Taif rose. It wears like candlelight on dark silk — quiet at first, then unforgettable.",
    storyAr:
      "عودٌ كمبودي يتّقد ببطء، يضيئه الزعفران ويليّنه الورد الطائفي. يلامس البشرة كضوء شمعة على حرير داكن — هادئ في البداية، ثم لا يُنسى.",
    bestseller: true, featured: true,
    pairs: ["amber-sultan", "rose-sahar"],
  },
  {
    slug: "rose-sahar",
    name: "Rose Sahar",
    nameAr: "ورد السَّحَر",
    kind: "FRAGRANCE",
    forms: ["PERFUME", "ATTAR"],
    tier: "classic",
    family: "FLORAL",
    gender: "WOMEN",
    shape: "facet",
    color: "#8c2338",
    moods: ["ROMANTIC", "CALM"],
    seasons: ["SPRING", "SUMMER"],
    times: ["DAY"],
    occasions: ["DATE", "EVERYDAY"],
    longevity: 4, sillage: 3, intensity: 3,
    notes: { top: ["bergamot", "pink-pepper"], heart: ["taif-rose", "damask-rose", "peony"], base: ["white-musk", "cedar"] },
    tagline: "Roses gathered before dawn.",
    taglineAr: "ورودٌ قُطفت قبل الفجر.",
    story:
      "Sahar is the hush before sunrise, when the rose fields of Taif are still heavy with dew. Two roses, a flicker of pink pepper and clean musk — romantic, never sweet.",
    storyAr:
      "السَّحَر هو سكون ما قبل الشروق، حين تكون حقول الورد في الطائف مثقلة بالندى. وردتان، وومضة من الفلفل الوردي، ومسك نقي — رومانسي من دون حلاوة زائدة.",
    bestseller: true,
    pairs: ["musk-noor", "oud-al-layl"],
  },
  {
    slug: "amber-sultan",
    name: "Amber Sultan",
    nameAr: "عنبر السلطان",
    kind: "FRAGRANCE",
    forms: ["PERFUME", "ATTAR"],
    tier: "luxe",
    family: "AMBER",
    gender: "UNISEX",
    shape: "round",
    color: "#c27c22",
    moods: ["CONFIDENT", "BALANCED"],
    seasons: ["AUTUMN", "WINTER"],
    times: ["NIGHT"],
    occasions: ["CELEBRATION", "DATE"],
    longevity: 5, sillage: 4, intensity: 4,
    notes: { top: ["cinnamon", "mandarin"], heart: ["labdanum", "benzoin"], base: ["vanilla", "tonka", "amber"] },
    tagline: "Warmth with a crown.",
    taglineAr: "دفءٌ يعتمر تاجاً.",
    story:
      "Resins warmed in the palm of a sultan — labdanum, benzoin and golden amber, opened with a flicker of cinnamon. Generous, glowing and made for winter evenings.",
    storyAr:
      "راتنجات دافئة في كفّ سلطان — لادن وجاوي وعنبر ذهبي، تفتتحها لمسة قرفة. سخيّ ومتوهّج، صُنع لأمسيات الشتاء.",
    bestseller: true, featured: true,
    pairs: ["oud-al-layl", "qahwa-noir"],
  },
  {
    slug: "musk-noor",
    name: "Musk Noor",
    nameAr: "مسك النور",
    kind: "FRAGRANCE",
    forms: ["PERFUME", "ATTAR"],
    tier: "classic",
    family: "MUSK",
    gender: "UNISEX",
    shape: "arch",
    color: "#e3d3ad",
    moods: ["CALM", "BALANCED"],
    seasons: ALL_SEASONS,
    times: ["DAY"],
    occasions: ["EVERYDAY", "PRAYER", "OFFICE"],
    longevity: 4, sillage: 2, intensity: 2,
    notes: { top: ["pear", "aldehydes"], heart: ["white-musk", "iris"], base: ["cashmeran", "ambrette"] },
    tagline: "Clean light on warm skin.",
    taglineAr: "ضوءٌ نقيّ على بشرة دافئة.",
    story:
      "A luminous white musk that smells like freshly pressed cotton and sunlight through linen. The scent people lean in to ask about — and the one you never take off.",
    storyAr:
      "مسك أبيض مضيء برائحة القطن المكويّ حديثاً وضوء الشمس عبر الكتان. العطر الذي يقترب الناس ليسألوا عنه — والذي لن ترغب في خلعه.",
    bestseller: true,
    pairs: ["rose-sahar", "sandal-sufi"],
  },
  {
    slug: "sandal-sufi",
    name: "Sandal Sufi",
    nameAr: "صندل صوفي",
    kind: "FRAGRANCE",
    forms: ["PERFUME", "ATTAR"],
    tier: "classic",
    family: "WOODY",
    gender: "UNISEX",
    shape: "facet",
    color: "#b5803f",
    moods: ["CALM", "FOCUSED"],
    seasons: ["AUTUMN", "MONSOON", "WINTER"],
    times: ["DAY", "NIGHT"],
    occasions: ["PRAYER", "EVERYDAY"],
    longevity: 4, sillage: 3, intensity: 3,
    notes: { top: ["cardamom"], heart: ["sandalwood", "jasmine"], base: ["vetiver", "musk"] },
    tagline: "A meditation in sandalwood.",
    taglineAr: "تأمّلٌ في خشب الصندل.",
    story:
      "Creamy Mysore sandalwood, a pinch of green cardamom and the faintest jasmine. Calm, centred and deeply comforting — the scent of a quiet courtyard at dusk.",
    storyAr:
      "صندل ميسور الكريمي، ورشّة من الهيل الأخضر، وهمسة ياسمين. هادئ ومتّزن ومريح بعمق — رائحة فناء ساكن عند الغروب.",
    pairs: ["musk-noor", "mitti"],
  },
  {
    slug: "mitti",
    name: "Mitti",
    nameAr: "مِتّي",
    kind: "FRAGRANCE",
    forms: ["ATTAR"],
    tier: "classic",
    family: "EARTHY",
    gender: "UNISEX",
    shape: "round",
    color: "#7a5332",
    moods: ["CALM", "BALANCED"],
    seasons: ["MONSOON", "SUMMER"],
    times: ["DAY"],
    occasions: ["EVERYDAY"],
    longevity: 3, sillage: 2, intensity: 2,
    notes: { top: ["petrichor"], heart: ["baked-earth", "vetiver"], base: ["sandalwood"] },
    tagline: "The first rain on summer earth.",
    taglineAr: "أول مطر على تراب الصيف.",
    story:
      "In Kannauj, discs of sun-baked clay are distilled into sandalwood oil to capture the smell of the first monsoon rain. Mitti is that moment — nostalgic, grounding, utterly Indian.",
    storyAr:
      "في قنّوج، تُقطَّر أقراص الطين المحمّص بالشمس في زيت الصندل لالتقاط رائحة أول مطر موسمي. مِتّي هو تلك اللحظة — حنين وثبات وروح هندية خالصة.",
    bestseller: true,
    pairs: ["sandal-sufi", "khus"],
  },
  {
    slug: "shamama",
    name: "Shamama",
    nameAr: "شمامة",
    kind: "FRAGRANCE",
    forms: ["ATTAR"],
    tier: "luxe",
    family: "SPICY",
    gender: "UNISEX",
    shape: "facet",
    color: "#7a3b16",
    moods: ["CONFIDENT", "CALM"],
    seasons: ["WINTER"],
    times: ["NIGHT"],
    occasions: ["CELEBRATION", "PRAYER"],
    longevity: 5, sillage: 4, intensity: 5,
    notes: { top: ["saffron", "clove"], heart: ["herbs", "kewda"], base: ["oud", "amber", "musk"] },
    tagline: "A winter fire of forty herbs.",
    taglineAr: "نارُ شتاءٍ من أربعين عشبة.",
    story:
      "A legendary winter attar slow-cooked for weeks from herbs, spices, flowers and resins. Dark, smoky and warming — a cashmere shawl for the soul.",
    storyAr:
      "عطر شتوي أسطوري يُطهى ببطء لأسابيع من الأعشاب والتوابل والزهور والراتنجات. داكن ودخاني ودافئ — شال من الكشمير للروح.",
    pairs: ["oud-malaki", "amber-sultan"],
  },
  {
    slug: "majmua",
    name: "Majmua",
    nameAr: "مجموعة",
    kind: "FRAGRANCE",
    forms: ["ATTAR"],
    tier: "classic",
    family: "HERBAL",
    gender: "UNISEX",
    shape: "round",
    color: "#8a6b2f",
    moods: ["BALANCED", "CALM"],
    seasons: ["SUMMER", "MONSOON"],
    times: ["DAY"],
    occasions: ["EVERYDAY", "PRAYER"],
    longevity: 3, sillage: 2, intensity: 3,
    notes: { top: ["kewda"], heart: ["vetiver", "kadam"], base: ["sandalwood"] },
    tagline: "A cool garden in high summer.",
    taglineAr: "حديقة باردة في عزّ الصيف.",
    story:
      "Majmua means 'collection' — a traditional Kannauj blend of kewda, khus and kadam blossom over sandalwood. Cooling, green and quietly sophisticated.",
    storyAr:
      "تعني مجموعة 'التشكيلة' — مزيج تقليدي من قنّوج يجمع الكيورا والخس وزهر الكدم فوق الصندل. منعش وأخضر وراقٍ في هدوء.",
    pairs: ["khus", "mitti"],
  },
  {
    slug: "khus",
    name: "Khus",
    nameAr: "خَس",
    kind: "FRAGRANCE",
    forms: ["ATTAR", "PERFUME"],
    tier: "classic",
    family: "FRESH",
    gender: "UNISEX",
    shape: "column",
    color: "#4f6b3a",
    moods: ["CALM", "FOCUSED"],
    seasons: ["SUMMER", "MONSOON"],
    times: ["DAY"],
    occasions: ["OFFICE", "EVERYDAY"],
    longevity: 3, sillage: 2, intensity: 2,
    notes: { top: ["green-leaves", "lime"], heart: ["vetiver"], base: ["sandalwood", "moss"] },
    tagline: "Shade under a vetiver screen.",
    taglineAr: "ظلٌّ تحت ستارة من نجيل الهند.",
    story:
      "Grandmothers once hung wet vetiver mats in doorways to cool the summer air. Khus is that green, rooty freshness — clean, cooling and endlessly wearable.",
    storyAr:
      "كانت الجدّات يعلّقن حُصُر نجيل الهند المبلّلة على الأبواب لتبريد هواء الصيف. خَس هو تلك النضارة الخضراء الجذرية — نقية ومنعشة وتُرتدى كل يوم.",
    offer: true,
    pairs: ["majmua", "noor-al-sabah"],
  },
  {
    slug: "ruh-gulab",
    name: "Ruh Gulab",
    nameAr: "روح الگلاب",
    kind: "FRAGRANCE",
    forms: ["ATTAR"],
    tier: "luxe",
    family: "FLORAL",
    gender: "WOMEN",
    shape: "facet",
    color: "#a3203a",
    moods: ["ROMANTIC", "CALM"],
    seasons: ["SPRING", "SUMMER"],
    times: ["DAY"],
    occasions: ["PRAYER", "DATE"],
    longevity: 4, sillage: 3, intensity: 3,
    notes: { top: ["rose-otto"], heart: ["damask-rose"], base: ["sandalwood"] },
    tagline: "The very soul of the rose.",
    taglineAr: "روح الوردة ذاتها.",
    story:
      "Ruh means soul. Thousands of hand-picked roses are steam-distilled the traditional deg-bhapka way to yield a few precious drops of rose otto. Pure, radiant and alive.",
    storyAr:
      "الروح هي الجوهر. تُقطَّر آلاف الورود المقطوفة يدوياً بالبخار على طريقة 'ديغ بهابكا' التقليدية لتمنح قطرات ثمينة من زيت الورد. نقي ومشرق ونابض بالحياة.",
    featured: true,
    pairs: ["rose-sahar", "musk-noor"],
  },
  {
    slug: "jannat-al-firdaus",
    name: "Jannat al-Firdaus",
    nameAr: "جنّة الفردوس",
    kind: "FRAGRANCE",
    forms: ["ATTAR", "PERFUME"],
    tier: "classic",
    family: "FLORAL",
    gender: "UNISEX",
    shape: "arch",
    color: "#d9b46a",
    moods: ["ROMANTIC", "BALANCED"],
    seasons: ["SPRING", "SUMMER"],
    times: ["DAY"],
    occasions: ["PRAYER", "CELEBRATION"],
    longevity: 4, sillage: 3, intensity: 3,
    notes: { top: ["lily", "basil"], heart: ["jasmine", "rose"], base: ["sandalwood", "musk"] },
    tagline: "A garden of paradise.",
    taglineAr: "حديقةٌ من الفردوس.",
    story:
      "A beloved classic of the Arabian world: lily and basil open onto jasmine and rose, settling into sandalwood and soft musk. Serene, joyful and timeless.",
    storyAr:
      "كلاسيكية محبوبة في العالم العربي: الزنبق والريحان ينفتحان على الياسمين والورد، ثم يستقرّان في الصندل والمسك الناعم. هادئ ومبهج وخالد.",
    pairs: ["musk-noor", "ruh-gulab"],
  },
  {
    slug: "zafran-royale",
    name: "Zafran Royale",
    nameAr: "زعفران رويال",
    kind: "FRAGRANCE",
    forms: ["PERFUME", "ATTAR"],
    tier: "luxe",
    family: "SPICY",
    gender: "MEN",
    shape: "column",
    color: "#9e3a1a",
    moods: ["CONFIDENT", "ENERGETIC"],
    seasons: ["AUTUMN", "WINTER"],
    times: ["NIGHT"],
    occasions: ["CELEBRATION", "DATE"],
    longevity: 5, sillage: 5, intensity: 5,
    notes: { top: ["saffron", "nutmeg"], heart: ["oud", "leather"], base: ["amber", "patchouli"] },
    tagline: "Saffron worn like a signet ring.",
    taglineAr: "زعفرانٌ يُرتدى كخاتم ملكي.",
    story:
      "Kashmiri saffron and nutmeg meet supple leather and dark oud. A commanding, resinous signature for evenings that deserve to be remembered.",
    storyAr:
      "زعفران كشميري وجوزة الطيب يلتقيان بالجلد الناعم والعود الداكن. توقيع آسر وراتنجي لأمسيات تستحق أن تُذكر.",
    isNew: true, featured: true,
    pairs: ["oud-al-layl", "malik"],
  },
  {
    slug: "layla",
    name: "Layla",
    nameAr: "ليلى",
    kind: "FRAGRANCE",
    forms: ["PERFUME", "ATTAR"],
    tier: "classic",
    family: "GOURMAND",
    gender: "WOMEN",
    shape: "round",
    color: "#6e2e4f",
    moods: ["ROMANTIC", "CONFIDENT"],
    seasons: ["AUTUMN", "WINTER"],
    times: ["NIGHT"],
    occasions: ["DATE", "CELEBRATION"],
    longevity: 4, sillage: 4, intensity: 4,
    notes: { top: ["plum", "raspberry"], heart: ["tuberose", "orange-blossom"], base: ["vanilla", "praline", "musk"] },
    tagline: "A love poem after dark.",
    taglineAr: "قصيدة حبٍّ بعد الغروب.",
    story:
      "Named for the heroine of the most famous love story in Arabic poetry. Velvet plum and tuberose melt into vanilla and praline — tender, magnetic, unforgettable.",
    storyAr:
      "سُمّي باسم بطلة أشهر قصة حب في الشعر العربي. برقوق مخملي ومسك الروم يذوبان في الفانيليا والبرالين — رقيق وجذّاب ولا يُنسى.",
    isNew: true,
    pairs: ["rose-sahar", "amber-sultan"],
  },
  {
    slug: "bahr",
    name: "Bahr",
    nameAr: "بحر",
    kind: "FRAGRANCE",
    forms: ["PERFUME"],
    tier: "classic",
    family: "FRESH",
    gender: "MEN",
    shape: "facet",
    color: "#2f6f8a",
    moods: ["ENERGETIC", "FOCUSED"],
    seasons: ["SUMMER", "SPRING"],
    times: ["DAY"],
    occasions: ["OFFICE", "TRAVEL"],
    longevity: 3, sillage: 3, intensity: 2,
    notes: { top: ["sea-salt", "grapefruit"], heart: ["sage", "marine-accord"], base: ["driftwood", "ambergris"] },
    tagline: "Salt air off the Arabian Sea.",
    taglineAr: "هواءٌ مالح من بحر العرب.",
    story:
      "A bracing sea breeze of salt, grapefruit and sage over sun-bleached driftwood. Effortless energy for long days and longer journeys.",
    storyAr:
      "نسيم بحري منعش من الملح والجريب فروت والمريمية فوق خشب شاطئ بيّضته الشمس. طاقة بلا عناء للأيام الطويلة والرحلات الأطول.",
    offer: true,
    pairs: ["noor-al-sabah", "saba"],
  },
  {
    slug: "noor-al-sabah",
    name: "Noor al-Sabah",
    nameAr: "نور الصباح",
    kind: "FRAGRANCE",
    forms: ["PERFUME"],
    tier: "classic",
    family: "CITRUS",
    gender: "UNISEX",
    shape: "arch",
    color: "#e0b84a",
    moods: ["ENERGETIC", "FOCUSED"],
    seasons: ["SUMMER", "SPRING"],
    times: ["DAY"],
    occasions: ["OFFICE", "EVERYDAY"],
    longevity: 3, sillage: 3, intensity: 2,
    notes: { top: ["bergamot", "neroli", "lemon"], heart: ["petitgrain", "orange-blossom"], base: ["white-musk", "cedar"] },
    tagline: "Morning light in a bottle.",
    taglineAr: "ضوء الصباح في قارورة.",
    story:
      "Sparkling bergamot and neroli, sunlit orange blossom and a clean musky trail. The bright, optimistic scent of a day that has only just begun.",
    storyAr:
      "برغموت ونيرولي متلألئان، وزهر برتقال مشمس، وأثر مسكي نقي. رائحة يوم مشرق ومتفائل بدأ للتوّ.",
    pairs: ["bahr", "khus"],
  },
  {
    slug: "malik",
    name: "Malik",
    nameAr: "مَلِك",
    kind: "FRAGRANCE",
    forms: ["PERFUME", "ATTAR"],
    tier: "classic",
    family: "WOODY",
    gender: "MEN",
    shape: "column",
    color: "#5a3e2a",
    moods: ["CONFIDENT", "FOCUSED"],
    seasons: ["AUTUMN", "WINTER"],
    times: ["DAY", "NIGHT"],
    occasions: ["OFFICE", "CELEBRATION"],
    longevity: 4, sillage: 4, intensity: 4,
    notes: { top: ["bergamot", "black-pepper"], heart: ["cedar", "vetiver"], base: ["leather", "oud", "tonka"] },
    tagline: "Quiet authority.",
    taglineAr: "هيبةٌ هادئة.",
    story:
      "Peppered bergamot, polished cedar and a whisper of oud on soft leather. Tailored, assured and unmistakably masculine — from the boardroom to the majlis.",
    storyAr:
      "برغموت بالفلفل، وأرز مصقول، وهمسة عود على جلد ناعم. أنيق وواثق ورجولي بلا شك — من قاعة الاجتماعات إلى المجلس.",
    bestseller: true,
    pairs: ["zafran-royale", "bahr"],
  },
  {
    slug: "yasmin",
    name: "Yasmin",
    nameAr: "ياسمين",
    kind: "FRAGRANCE",
    forms: ["PERFUME", "ATTAR"],
    tier: "classic",
    family: "FLORAL",
    gender: "WOMEN",
    shape: "facet",
    color: "#e9d9a8",
    moods: ["ROMANTIC", "ENERGETIC"],
    seasons: ["SPRING", "SUMMER"],
    times: ["NIGHT"],
    occasions: ["DATE", "CELEBRATION"],
    longevity: 4, sillage: 4, intensity: 3,
    notes: { top: ["mandarin"], heart: ["jasmine-sambac", "tuberose"], base: ["musk", "sandalwood"] },
    tagline: "Mogra strung through your hair.",
    taglineAr: "عقدٌ من الفلّ بين خصلات شعرك.",
    story:
      "Night-blooming jasmine sambac — the mogra of Indian weddings — wrapped in tuberose and sandalwood. Heady, joyful and gloriously feminine.",
    storyAr:
      "فلّ يتفتح ليلاً — زهرة الأعراس الهندية — ملفوف بمسك الروم والصندل. آسر ومبهج وأنثوي بروعة.",
    offer: true,
    pairs: ["rose-sahar", "layla"],
  },
  {
    slug: "hina",
    name: "Hina",
    nameAr: "حِنّا",
    kind: "FRAGRANCE",
    forms: ["ATTAR"],
    tier: "classic",
    family: "EARTHY",
    gender: "WOMEN",
    shape: "round",
    color: "#7b4a1e",
    moods: ["CALM", "ROMANTIC"],
    seasons: ["WINTER", "MONSOON"],
    times: ["NIGHT"],
    occasions: ["CELEBRATION"],
    longevity: 5, sillage: 3, intensity: 4,
    notes: { top: ["henna"], heart: ["clove", "saffron"], base: ["sandalwood", "amber"] },
    tagline: "The scent of a wedding night.",
    taglineAr: "عبقُ ليلة الزفاف.",
    story:
      "Distilled from henna blossom and warm spices, Hina is the fragrance of mehndi evenings — earthy, sensual and steeped in celebration.",
    storyAr:
      "مقطّر من زهر الحنّاء والتوابل الدافئة، حِنّا هو عطر ليالي الحنّاء — ترابي وحسّي ومشبع بالاحتفال.",
    pairs: ["shamama", "layla"],
  },
  {
    slug: "kewda-breeze",
    name: "Kewda Breeze",
    nameAr: "نسيم الكيورا",
    kind: "FRAGRANCE",
    forms: ["PERFUME", "ATTAR"],
    tier: "classic",
    family: "FRESH",
    gender: "UNISEX",
    shape: "arch",
    color: "#b9c98f",
    moods: ["CALM", "ENERGETIC"],
    seasons: ["SUMMER", "MONSOON"],
    times: ["DAY"],
    occasions: ["EVERYDAY", "TRAVEL"],
    longevity: 3, sillage: 2, intensity: 2,
    notes: { top: ["kewda", "lime"], heart: ["green-tea"], base: ["musk"] },
    tagline: "Green, cool and sweetly airy.",
    taglineAr: "أخضر وبارد وخفيف بعذوبة.",
    story:
      "Kewda — the fragrant pandanus flower of coastal India — meets lime and green tea for a breezy, cooling freshness made for humid days.",
    storyAr:
      "الكيورا — زهرة الباندان العطرة من سواحل الهند — تلتقي بالليم والشاي الأخضر لنضارة منعشة خُلقت للأيام الرطبة.",
    isNew: true,
    pairs: ["khus", "saba"],
  },
  {
    slug: "oud-malaki",
    name: "Oud Malaki",
    nameAr: "عود ملكي",
    kind: "FRAGRANCE",
    forms: ["ATTAR"],
    tier: "luxe",
    family: "OUD",
    gender: "MEN",
    shape: "facet",
    color: "#2b1a10",
    moods: ["CONFIDENT"],
    seasons: ["WINTER", "AUTUMN"],
    times: ["NIGHT"],
    occasions: ["CELEBRATION", "PRAYER"],
    longevity: 5, sillage: 5, intensity: 5,
    notes: { top: ["oud"], heart: ["incense"], base: ["sandalwood", "ambergris"] },
    tagline: "Pure oud, aged like royalty.",
    taglineAr: "عودٌ خالص، معتّق كالملوك.",
    story:
      "Our rarest oil: wild agarwood distilled and aged in small batches. Animalic, honeyed and profound — a single drop fills a room for hours.",
    storyAr:
      "أندر زيوتنا: عود بري مقطّر ومعتّق على دفعات صغيرة. حيواني الطابع وعسلي وعميق — قطرة واحدة تملأ المكان لساعات.",
    featured: true,
    pairs: ["shamama", "oud-al-layl"],
  },
  {
    slug: "saba",
    name: "Saba",
    nameAr: "صَبا",
    kind: "FRAGRANCE",
    forms: ["PERFUME"],
    tier: "classic",
    family: "HERBAL",
    gender: "UNISEX",
    shape: "round",
    color: "#8fb3a0",
    moods: ["CALM", "BALANCED"],
    seasons: ["SPRING", "SUMMER"],
    times: ["DAY"],
    occasions: ["EVERYDAY", "TRAVEL"],
    longevity: 3, sillage: 2, intensity: 2,
    notes: { top: ["mint", "cucumber"], heart: ["lavender", "sage"], base: ["musk"] },
    tagline: "The gentle east wind.",
    taglineAr: "ريح الصَّبا اللطيفة.",
    story:
      "In Arabic poetry, Saba is the soft easterly breeze that carries news of the beloved. Mint, lavender and sage on a cool musk — calm in a bottle.",
    storyAr:
      "في الشعر العربي، الصَّبا هي الريح الشرقية اللطيفة التي تحمل أخبار الحبيب. نعناع وخزامى ومريمية على مسك بارد — سكينة في قارورة.",
    offer: true,
    pairs: ["musk-noor", "kewda-breeze"],
  },
  {
    slug: "qahwa-noir",
    name: "Qahwa Noir",
    nameAr: "قهوة نوار",
    kind: "FRAGRANCE",
    forms: ["PERFUME", "ATTAR"],
    tier: "classic",
    family: "GOURMAND",
    gender: "UNISEX",
    shape: "column",
    color: "#4b2a18",
    moods: ["CONFIDENT", "FOCUSED"],
    seasons: ["WINTER", "AUTUMN"],
    times: ["NIGHT"],
    occasions: ["DATE", "CELEBRATION"],
    longevity: 4, sillage: 4, intensity: 4,
    notes: { top: ["cardamom"], heart: ["coffee", "rose"], base: ["oud", "vanilla"] },
    tagline: "Arabian coffee, poured slowly.",
    taglineAr: "قهوة عربية تُصبّ على مهل.",
    story:
      "Cardamom-laced Arabian coffee, a rose from the dallah tray and a velvety base of oud and vanilla. The ritual of hospitality, worn on skin.",
    storyAr:
      "قهوة عربية بالهيل، ووردة من صينية الدلّة، وقاعدة مخملية من العود والفانيليا. طقس الضيافة على البشرة.",
    isNew: true,
    pairs: ["amber-sultan", "oud-al-layl"],
  },
  {
    slug: "ambergris-sky",
    name: "Ambergris Sky",
    nameAr: "عنبر السماء",
    kind: "FRAGRANCE",
    forms: ["PERFUME"],
    tier: "classic",
    family: "AMBER",
    gender: "UNISEX",
    shape: "arch",
    color: "#d9c3a0",
    moods: ["BALANCED", "CALM"],
    seasons: ALL_SEASONS,
    times: ["DAY"],
    occasions: ["OFFICE", "TRAVEL", "EVERYDAY"],
    longevity: 4, sillage: 3, intensity: 2,
    notes: { top: ["sea-salt", "bergamot"], heart: ["ambergris", "iris"], base: ["white-musk", "cashmeran"] },
    tagline: "Salt-kissed skin under an open sky.",
    taglineAr: "بشرةٌ قبّلها الملح تحت سماء مفتوحة.",
    story:
      "Mineral ambergris, powdery iris and a soft cloud of musk. Airy yet tenacious — the scent of your own skin, only better.",
    storyAr:
      "عنبر رمادي معدني، وسوسن بودري، وغيمة ناعمة من المسك. خفيف لكنه ثابت — رائحة بشرتك، لكن أجمل.",
    pairs: ["musk-noor", "bahr"],
  },
  {
    slug: "bakhoor-nights",
    name: "Bakhoor Nights",
    nameAr: "ليالي البخور",
    kind: "FRAGRANCE",
    forms: ["PERFUME", "ATTAR"],
    tier: "luxe",
    family: "OUD",
    gender: "UNISEX",
    shape: "round",
    color: "#5a2a1e",
    moods: ["ROMANTIC", "CONFIDENT"],
    seasons: ["WINTER", "AUTUMN"],
    times: ["NIGHT"],
    occasions: ["CELEBRATION", "DATE"],
    longevity: 5, sillage: 5, intensity: 4,
    notes: { top: ["incense", "saffron"], heart: ["oud", "rose"], base: ["amber", "labdanum"] },
    tagline: "Smoke curling from the mabkhara.",
    taglineAr: "دخانٌ يتلوّى من المبخرة.",
    story:
      "Inspired by bakhoor smouldering in a brass mabkhara to welcome guests — incense, saffron and rose over glowing oud and amber. Smoky, sweet and ceremonial.",
    storyAr:
      "مستوحى من البخور المتّقد في مبخرة نحاسية لاستقبال الضيوف — بخور وزعفران وورد فوق عود وعنبر متوهّجين. دخاني وعذب ومهيب.",
    bestseller: true,
    pairs: ["oud-al-layl", "qahwa-noir"],
  },

  // ─── Therapies ───────────────────────────────────────────────────────────
  {
    slug: "sukoon-stress-relief",
    name: "Sukoon",
    nameAr: "سكون",
    kind: "THERAPY",
    forms: ["OIL"],
    family: "HERBAL",
    gender: "UNISEX",
    color: "#7f9c8a",
    moods: ["CALM", "BALANCED"],
    needs: ["STRESS"],
    seasons: ALL_SEASONS,
    times: ["DAY", "NIGHT"],
    occasions: ["EVERYDAY"],
    notes: { top: ["bergamot"], heart: ["lavender"], base: ["frankincense"] },
    tagline: "Stress relief blend",
    taglineAr: "مزيج لتخفيف التوتر",
    story:
      "Sukoon means stillness. Lavender, bergamot and frankincense come together in a soothing aromatherapy blend to help you pause, breathe and unwind after a demanding day.",
    storyAr:
      "السكون هو الهدوء. تجتمع الخزامى والبرغموت واللبان في مزيج عطري مهدّئ يساعدك على التوقّف والتنفّس والاسترخاء بعد يوم مرهق.",
    bestseller: true,
    pairs: ["layl-better-sleep", "mizan-emotional-balance"],
  },
  {
    slug: "layl-better-sleep",
    name: "Layl",
    nameAr: "ليل",
    kind: "THERAPY",
    forms: ["OIL"],
    family: "HERBAL",
    gender: "UNISEX",
    color: "#6a5c8e",
    moods: ["CALM"],
    needs: ["SLEEP"],
    seasons: ALL_SEASONS,
    times: ["NIGHT"],
    occasions: ["EVERYDAY"],
    notes: { top: ["chamomile"], heart: ["lavender"], base: ["cedar"] },
    tagline: "Better sleep ritual",
    taglineAr: "طقس لنومٍ أهنأ",
    story:
      "A bedtime blend of lavender, chamomile and cedarwood, created to make winding down feel like a ritual. Diffuse an hour before bed or massage gently into the temples.",
    storyAr:
      "مزيج لوقت النوم من الخزامى والبابونج وخشب الأرز، صُمّم ليجعل الاسترخاء طقساً. انشره قبل النوم بساعة أو دلّك به الصدغين بلطف.",
    bestseller: true,
    pairs: ["sukoon-stress-relief"],
  },
  {
    slug: "nashat-focus-energy",
    name: "Nashat",
    nameAr: "نشاط",
    kind: "THERAPY",
    forms: ["OIL"],
    family: "HERBAL",
    gender: "UNISEX",
    color: "#c9a23a",
    moods: ["ENERGETIC", "FOCUSED"],
    needs: ["FOCUS"],
    seasons: ALL_SEASONS,
    times: ["DAY"],
    occasions: ["OFFICE"],
    notes: { top: ["peppermint", "lemon"], heart: ["rosemary"], base: ["cedar"] },
    tagline: "Focus & energy oil",
    taglineAr: "زيت للتركيز والطاقة",
    story:
      "Peppermint, rosemary and lemon — a bright, invigorating blend for the desk, the commute or the mid-afternoon slump.",
    storyAr:
      "نعناع فلفلي وإكليل الجبل وليمون — مزيج مشرق ومنعش للمكتب أو الطريق أو فتور منتصف الظهيرة.",
    offer: true,
    pairs: ["noor-al-sabah"],
  },
  {
    slug: "shifa-skin-hair",
    name: "Shifa",
    nameAr: "شفاء",
    kind: "THERAPY",
    forms: ["OIL"],
    family: "HERBAL",
    gender: "UNISEX",
    color: "#b5803f",
    moods: ["BALANCED"],
    needs: ["SKIN_HAIR"],
    seasons: ALL_SEASONS,
    times: ["NIGHT"],
    occasions: ["EVERYDAY"],
    notes: { top: ["kumkumadi-saffron"], heart: ["rosehip"], base: ["argan"] },
    tagline: "Skin & hair elixir",
    taglineAr: "إكسير للبشرة والشعر",
    story:
      "A nourishing facial and hair oil of argan, rosehip and saffron, inspired by the Ayurvedic kumkumadi tradition. Leaves skin soft and hair glossy.",
    storyAr:
      "زيت مغذٍّ للوجه والشعر من الأرغان وثمر الورد والزعفران، مستوحى من تقليد كومكومادي الأيورفيدي. يترك البشرة ناعمة والشعر لامعاً.",
    pairs: ["mizan-emotional-balance"],
  },
  {
    slug: "mizan-emotional-balance",
    name: "Mizan",
    nameAr: "ميزان",
    kind: "THERAPY",
    forms: ["OIL"],
    family: "FLORAL",
    gender: "UNISEX",
    color: "#a37a8c",
    moods: ["BALANCED", "CALM"],
    needs: ["BALANCE"],
    seasons: ALL_SEASONS,
    times: ["DAY", "NIGHT"],
    occasions: ["EVERYDAY"],
    notes: { top: ["geranium"], heart: ["ylang-ylang"], base: ["sandalwood"] },
    tagline: "Emotional balance blend",
    taglineAr: "مزيج للتوازن العاطفي",
    story:
      "Mizan means balance. Rose geranium, ylang-ylang and sandalwood form a gentle, grounding blend for days that feel a little off-centre.",
    storyAr:
      "الميزان هو التوازن. إبرة الراعي واليلانغ يلانغ والصندل في مزيج لطيف ومثبّت للأيام التي تبدو فيها الأمور خارج مسارها.",
    pairs: ["sukoon-stress-relief"],
  },
  {
    slug: "nafas-breathe-easy",
    name: "Nafas",
    nameAr: "نَفَس",
    kind: "THERAPY",
    forms: ["OIL"],
    family: "HERBAL",
    gender: "UNISEX",
    color: "#5e8f8a",
    moods: ["ENERGETIC", "CALM"],
    needs: ["STRESS", "FOCUS"],
    seasons: ["MONSOON", "WINTER"],
    times: ["DAY", "NIGHT"],
    occasions: ["EVERYDAY", "TRAVEL"],
    notes: { top: ["eucalyptus"], heart: ["peppermint"], base: ["tea-tree"] },
    tagline: "Breathe-easy steam blend",
    taglineAr: "مزيج بخار للتنفّس بارتياح",
    story:
      "Eucalyptus, peppermint and tea tree for a clarifying steam or diffuser ritual — especially welcome through the monsoon and winter months.",
    storyAr:
      "أوكالبتوس ونعناع فلفلي وشجرة الشاي لطقس بخار أو انتشار منعش — مرحّب به خاصة في أشهر الموسم الماطر والشتاء.",
    isNew: true,
    pairs: ["sukoon-stress-relief"],
  },

  // ─── Gift sets ───────────────────────────────────────────────────────────
  {
    slug: "the-royal-edit",
    name: "The Royal Edit",
    nameAr: "التشكيلة الملكية",
    kind: "GIFT_SET",
    forms: ["SET"],
    gender: "UNISEX",
    color: "#c9a55c",
    occasions: ["CELEBRATION"],
    tagline: "Three icons, one keepsake box",
    taglineAr: "ثلاث أيقونات في صندوق تذكاري",
    story:
      "Our three most-loved evening fragrances in 50 ml, presented in a hand-finished noir box with gold arches.",
    storyAr: "أحبّ ثلاثة عطور مسائية لدينا بحجم ٥٠ مل، في صندوق أسود مصقول يدوياً بأقواس ذهبية.",
    setPrice: 7499, setMrp: 8999,
    setContents: "Oud al-Layl 50 ml · Amber Sultan 50 ml · Malik 50 ml",
    setContentsAr: "عود الليل ٥٠ مل · عنبر السلطان ٥٠ مل · مَلِك ٥٠ مل",
    featured: true, bestseller: true, sampleable: false,
  },
  {
    slug: "attar-treasury",
    name: "Attar Treasury",
    nameAr: "خزانة العطور الزيتية",
    kind: "GIFT_SET",
    forms: ["SET"],
    gender: "UNISEX",
    color: "#a8803e",
    occasions: ["CELEBRATION", "PRAYER"],
    tagline: "Six heritage attars",
    taglineAr: "ستة عطور زيتية تراثية",
    story:
      "Six 3 ml attars from the Kannauj tradition — Mitti, Shamama, Majmua, Khus, Ruh Gulab and Jannat al-Firdaus — nestled in a carved wooden chest.",
    storyAr:
      "ستة عطور زيتية بحجم ٣ مل من تقاليد قنّوج — مِتّي وشمامة ومجموعة وخَس وروح الگلاب وجنّة الفردوس — في صندوق خشبي منقوش.",
    setPrice: 3499, setMrp: 4194,
    setContents: "6 × 3 ml attars in a carved wooden chest",
    setContentsAr: "٦ × ٣ مل عطور زيتية في صندوق خشبي منقوش",
    featured: true, sampleable: false,
  },
  {
    slug: "her-rose-garden",
    name: "Her Rose Garden",
    nameAr: "حديقة الورد",
    kind: "GIFT_SET",
    forms: ["SET"],
    gender: "WOMEN",
    color: "#8c2338",
    occasions: ["DATE", "CELEBRATION"],
    tagline: "Rose, two ways",
    taglineAr: "الورد بطريقتين",
    story: "Rose Sahar Eau de Parfum 50 ml with Ruh Gulab pure attar 6 ml — the rose as a spray and as a soul.",
    storyAr: "عطر ورد السَّحَر ٥٠ مل مع عطر روح الگلاب الزيتي الخالص ٦ مل — الورد رذاذاً وروحاً.",
    setPrice: 3499, setMrp: 3898,
    setContents: "Rose Sahar EDP 50 ml · Ruh Gulab attar 6 ml",
    setContentsAr: "ورد السَّحَر ٥٠ مل · روح الگلاب ٦ مل",
    sampleable: false,
  },
  {
    slug: "calm-ritual-box",
    name: "Calm Ritual Box",
    nameAr: "صندوق طقوس السكينة",
    kind: "GIFT_SET",
    forms: ["SET"],
    gender: "UNISEX",
    color: "#7f9c8a",
    occasions: ["EVERYDAY"],
    needs: ["STRESS", "SLEEP"],
    tagline: "Wind down, beautifully",
    taglineAr: "استرخِ بأناقة",
    story: "Sukoon and Layl therapy oils (30 ml each) with a ceramic diffuser stone — a gift of rest.",
    storyAr: "زيتا سكون وليل (٣٠ مل لكل منهما) مع حجر خزفي لنشر العطر — هدية من الراحة.",
    setPrice: 2299, setMrp: 2698,
    setContents: "Sukoon 30 ml · Layl 30 ml · ceramic diffuser stone",
    setContentsAr: "سكون ٣٠ مل · ليل ٣٠ مل · حجر خزفي لنشر العطر",
    offer: true, sampleable: false,
  },
  {
    slug: "festive-celebration-set",
    name: "Festive Celebration Set",
    nameAr: "طقم الاحتفال",
    kind: "GIFT_SET",
    forms: ["SET"],
    gender: "UNISEX",
    color: "#b38a3e",
    occasions: ["CELEBRATION"],
    tagline: "For Eid, Diwali & every celebration",
    taglineAr: "للعيد وديوالي وكل احتفال",
    story:
      "Bakhoor Nights 50 ml, Jannat al-Firdaus attar 6 ml and Musk Noor 30 ml with a hand-written card — joy, wrapped in gold.",
    storyAr: "ليالي البخور ٥٠ مل، وجنّة الفردوس ٦ مل، ومسك النور ٣٠ مل مع بطاقة مكتوبة بخط اليد — فرحة ملفوفة بالذهب.",
    setPrice: 4999, setMrp: 5797,
    setContents: "Bakhoor Nights 50 ml · Jannat al-Firdaus attar 6 ml · Musk Noor 30 ml",
    setContentsAr: "ليالي البخور ٥٠ مل · جنّة الفردوس ٦ مل · مسك النور ٣٠ مل",
    isNew: true, sampleable: false,
  },

  // ─── Discovery set (built by the customer) ───────────────────────────────
  {
    slug: "discovery-set",
    name: "Build Your Discovery Set",
    nameAr: "اصنع مجموعة الاكتشاف",
    kind: "DISCOVERY_SET",
    forms: ["SET"],
    gender: "UNISEX",
    color: "#c9a55c",
    tagline: "Any five scents · 2 ml each",
    taglineAr: "أي خمسة عطور · ٢ مل لكل منها",
    story:
      "Choose any five perfumes or attars as 2 ml vials, presented in a gold-lined tray. Live with them for a week, then choose your signature.",
    storyAr:
      "اختر أي خمسة عطور أو عطور زيتية في قوارير بحجم ٢ مل، تُقدَّم في صينية مبطّنة بالذهب. جرّبها أسبوعاً ثم اختر عطرك المميز.",
    setPrice: 999,
    setContents: "5 × 2 ml vials of your choice",
    setContentsAr: "٥ × ٢ مل من اختيارك",
    sampleable: false,
  },
];
